### PR TITLE
Bump ECOS_jll

### LINKED ISSUE #116: Update ECOS_jll to 2.0.8
x-ref: https://github.com/JuliaPackaging/Yggdrasil/pull/2702

### PR DESCRIPTION
**Pull request by odow**
Closes #116

### CODE REVIEW

**Comment by odow** [comment]
Hmm weird error on Windows only.
```Julia
Test the direct interface: Error During Test at D:\a\ECOS.jl\ECOS.jl\test\runtests.jl:14
  Got exception outside of a @test
  LoadError: ECOS failed to construct problem.
  Stacktrace:
   [1] error(::String) at .\error.jl:33
   [2] setup(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Array{Int64,1}, ::Int64, ::ECOS.ECOSMatrix, ::ECOS.ECOSMatrix, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at D:\a\ECOS.jl\ECOS.jl\src\ECOS.jl:121
   [3] setup at D:\a\ECOS.jl\ECOS.jl\src\ECOS.jl:106 [inlined]
   [4] test1() at D:\a\ECOS.jl\ECOS.jl\test\direct.jl:49
   [5] top-level scope at D:\a\ECOS.jl\ECOS.jl\test\direct.jl:58
   [6] include(::String) at .\client.jl:457
   [7] top-level scope at D:\a\ECOS.jl\ECOS.jl\test\runtests.jl:15
   [8] top-level scope at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Test\src\Test.jl:1119
   [9] top-level scope at D:\a\ECOS.jl\ECOS.jl\test\runtests.jl:15
   [10] include(::String) at .\client.jl:457
   [11] top-level scope at none:6
   [12] eval(::Module, ::Any) at .\boot.jl:347
   [13] exec_options(::Base.JLOptions) at .\client.jl:272
   [14] _start() at .\client.jl:506
  in expression starting at D:\a\ECOS.jl\ECOS.jl\test\direct.jl:58
```

**Comment by odow** [comment]
Anyone have ideas? I'm guessing we need to set some flag when compiling on windows, but I couldn't see any obvious culprits: https://github.com/embotech/ecos/compare/v2.0.5...v2.0.8

**Comment by metab0t** [comment]
I spent an afternoon on this issue and I think this change is the root cause:

https://github.com/embotech/ecos/blob/fcdbcc8dd221b8b2a556b2d90f52e47a749c9695/external/SuiteSparse_config/SuiteSparse_config.h#L54

https://github.com/embotech/ecos/blob/6f55a86080dac75b5df34ce1135cafda1c2053c0/external/SuiteSparse_config/SuiteSparse_config.h#L53

In version 2.0.5, MinGW does not define `_MSC_VER` so `idxint` is defined as `long` the same as other platforms.
In current version, `idxint` is defined as `__int64`  rather than `long` on Windows (`sizeof(long)=4` but `sizeof(__int64)=8` on Windows), but the generated Julia binding still assumes `idxint = Clong` and caused error.

The easiest solution would be adding `-D_MSC_VER` when building `ECOS_jll`. I am not familiar with BinaryBuilder so I haven't tried it.

**Comment by odow** [comment]
Thanks for looking into this!

It might be sufficient to just change this line:
https://github.com/jump-dev/ECOS.jl/blob/34508710f029413b7409f8bb4dc52b5baaae5a56/src/gen/libecos_common.jl#L7
assuming the library is built correctly for Windows.

Something like
```Julia
const idxint = @static Sys.iswindows() ? Int64 : Clong  # Or something
```

Isn't `Clong` just an alias for Int64 though?
```julia
julia> Clong
Int64
```
Or is it different on Windows?

In which case maybe it's just
```Julia
const idxint = Int64
```

**Comment by metab0t** [comment]
`Clong` is an alias of `Int32` on Windows.

This is fine in my opinion because it is identical to the logic in `SuiteSparse_config.h`.
```
const idxint = @static Sys.iswindows() ? Int64 : Clong
```

**Comment by odow** [comment]
Hmm. I guess CI won't run until I fix the conflicts. If you're interested and have time, please feel free to copy-paste any of the changes I made into a new PR!

**Comment by metab0t** [comment]
I will try to update the C-API generation script to use the newest `Clang.jl` when I have more time. `Clang.jl` has overhauled its generation interface recently.

**Comment by odow** [comment]
Closing in favor of #128

**Pull request closed without merging**
